// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'darkShell': string;
  'docsNav': string;
  'docsNavBrand': string;
  'docsNavInner': string;
  'docsNavLink': string;
  'docsNavLinkActive': string;
  'docsNavLinks': string;
  'documentArea': string;
  'documentContent': string;
  'documentationShell': string;
  'hero': string;
  'heroInner': string;
  'heroMark': string;
  'heroSubtitle': string;
  'heroText': string;
  'heroTitle': string;
  'lightShell': string;
}
export const cssExports: CssExports;
export default cssExports;
