apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carbonorm-docs
  namespace: carbonorm
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - carbonorm.miles.systems
      secretName: carbonorm-docs-miles-systems-tls
  rules:
    - host: carbonorm.miles.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carbonorm-docs
                port:
                  name: http
